### ISSUE TITLE
Error documentation

### ISSUE THREAD

**Issue by banstola** [Sage/sageone_api_php_sample#17]
Do you have a documentation on what kind of error messages to expect  from different request from the API so that we can have a better error handling while using the API?

**Comment by cpetschnig** [comment]
Sorry, we don't have it currently. We are looking to improve the documentation in the next months and describing the errors is already on our list of improvements.

**Comment by banstola** [comment]
While on this topic ... what is the rate for making request to the API?

**Comment by cpetschnig** [comment]
We've currently set it to 200 requests per minute. But please don't rely on it, as we may increase or decrease it based on our experience. Better handle `429` responses and retry after a short while.

**Comment by banstola** [comment]
Until you make those error documents, what is the right channel to ask error related questions? Is github the right channel?  I have been getting following error message back. What does it mean ?

**You cannot edit VAT reconciled transactions.**

**Comment by timlapluie** [comment]
@banstola: Currently, Github is a good place to ask questions. 

The message `You cannot edit VAT reconciled transactions.` is an application error message. It indicates that you try to change e.g. an invoice for which you already created a VAT return:
After an invoice belongs to a VAT return, it is not possible anymore to change this invoice because this would make the already created VAT return wrong.
