### ISSUE TITLE
Invalid grant response from access token request

### ISSUE THREAD

**Issue by Quacky2200** [Sage/sageone_api_php_sample#23]
Hi,

I am trying to make an implementation with this with most of the code based around the sample code. However whenever I try to get an access token I keep getting `{"error":"invalid_grant"}`. I decided to revert back to the PHP sample code since I thought I must be doing something wrong however I'm getting the same issue over and over again.  I have even tried waiting 15 minutes to a whole day in case it was some kind of timeout.

I decided to try with a curl command which can be seen below.
![access token](https://user-images.githubusercontent.com/4623599/29404952-67654836-8334-11e7-8bbb-3cf6c4a9f939.png)

Any help would be appreciated.

**Comment by cpetschnig** [comment]
Hi Matthew,

you have only 60 seconds to exchange the code you received on the callback for an access token using the token endpoint (like in the curl example you showed).

Would this fix it?

Cheers,
Christoph

**Comment by Quacky2200** [comment]
Unfortunately this won't work since the process is automated both on PHP sample and my code. It will automatically redirect and then attempt to get the token as soon as possible so it's not expiring after 60 seconds.

I saw in [another comment](https://github.com/Sage/sageone_api_php_sample/issues/9#issuecomment-288351098) that I cannot use the Sage One API with multiple clients and only as part of the same business who created the API. Could this potentially be the issue I'm facing or would I never have gotten to the 'authorise' point with the user?

**Comment by cpetschnig** [comment]
I can offer you a support call. Can you email me so we can set up a call?

**Comment by NeonHorizon** [comment]
It seems we have 3 issues which are all connected.
As mentioned in the other posts we had a version of this code in production then it suddenly stopped working. The original get_file_contents doesn't display the error but as mentioned you can retrieve it with curl and it is indeed {"error":"invalid_grant"}

Since it happens in file_get_contents and curl and many of us are seeing it on different servers I'm beginning to this its an issue at Sage's end so I have opened a support ticket with them to see what else I can find out.

**Comment by NeonHorizon** [comment]
OK I finally have a solution to our problem, yours might not be related but the information maybe helpful....

It turns out Sage are using invalid_grant as a catch all error message so problems during either the authorisation redirect or the token fetch can cause the error even if they are nothing to do with the grant setting.

In our case the problem was in the configuration file we were dynamically setting the callback url depending on what part of our application required access. It turns out that when we were doing the authorisation redirect our callback_url URL had a slightly different query string to when we did the token request and this was enough to trigger the error.

What suddenly caused the problem seems to be the Sage changed their authorisation response to include state in the query string which it didn't previously for our region. This got confused with the applications query string resulting in the URL's not matching.

I hope this helps someone...

**Comment by papiermache** [comment]
Thx for providing the info; wasted a few hours on this. But really Sage folk, wake up - what is the point of a totally useless 'default' error message that sends your unsuspeting developers down the garden path ..
Also the '60 second' constraint, first I've heard of that, where is it documented (certainly not in the quick-start guides)?

**Comment by NucsuM** [comment]
Thanks @NeonHorizon for your investigation and that you support other developer that may have the same problem.

Hello @papiermache , thanks for your feedback and I regret that you wasted time because you did not find the right information in our documentation. We are constantly improving our documentation by hints from developer like you. The part with the 60 seconds is documented in this section of the documentation [Frequently Raised Errors](https://developer.sage.com/api/accounting/guides/frequently_raised_errors/).

Regards, Robert

**Comment by papiermache** [comment]
A bit of an obtuse place, no? Why not in the the actual documenation and accompanying sample code – proatively so that folks can know (and code) in advance, rather than strange errors and not many minutes, or hours, of debuggering ..
