### ISSUE TITLE
reliable version of execApiRequest

### ISSUE THREAD

**Issue by AlanBell** [Sage/sageone_api_php_sample#58]
it would  be good to have a method that wraps the execApiRequest method and deals with renewing the token if necessary.
So this would call execApiRequest, and look at the response, if it is an access token timeout error it would renew the access token and call execAPIRequest a second time, then return whatever that response is without looking at it. So, if it hits an expired token it will make a single attempt to renew it and try again.

**Comment by NucsuM** [comment]
Thanks @AlanBell for your ideas which could improve this application. The idea of the API sample apps are, to provide a very basic example how the Sage Business Cloud Accounting API. Not bloated and easy to understand. If somebody need this feature in his own application, it would maybe implement this in his own application.

So that is my personal opinion about this topic. But I will take your idea to the next update round of this application.

If you have questions about the Sage Business Cloud Accounting API or want to report problems, then the [accounting api section of sagecity.com](https://www.sagecity.com/developer/accounting-api/) is the perfect place.
